### ISSUE TITLE
Command Line Usage? 

### ISSUE THREAD

**Issue by ProGamerGov** [crowsonkb/deep_dream#1]
Is there a way to use this with the command line instead of the Notebook software?

**Comment by crowsonkb** [comment]
Not yet. It should not be very difficult to write a CLI, though.

**Comment by ProGamerGov** [comment]
What about taking the CLI from this: https://github.com/kesara/deepdreamer and using it on your modified code? I have done it with deep dream itself, but not with a modified tile system.

**Comment by ProGamerGov** [comment]
I ran `$ ipython nbconvert --to python deep_dream.ipynb` to convert it to a python script. But now I get the following error:

```
ubuntu@ip-Address:~/deep_dream$ python deep_dream.py
Traceback (most recent call last):
  File "deep_dream.py", line 12, in <module>
    import deep_dream
  File "/home/ubuntu/deep_dream/deep_dream/__init__.py", line 1, in <module>
    from .deep_dream import CNN, EPS, ShapeError, call_normalized, normf, save_as_hdr, to_image
  File "/home/ubuntu/deep_dream/deep_dream/deep_dream.py", line 8, in <module>
    from pathlib import Path
ImportError: No module named pathlib
ubuntu@ip-Address:~/deep_dream$

```
