### ISSUE TITLE
 How would I save the output image as it's own file in my deep_deep folder?

### ISSUE THREAD

**Issue by ProGamerGov** [crowsonkb/deep_dream#7]
I have noticed an issue where the output image can be too large for you to download it via right clicking and saving in the browser. 

How would I save the output image as it's own file in my deep_deep folder?

**Comment by crowsonkb** [comment]
If I assigned the output of dream() to, say, 'img2':

```img2 = cnn.dream(...```

then I can do: ```dd.to_image(img2).save('output_folder/out.jpg', quality=95)``` (quality is for jpeg only and is omitted for png).

I can also do: ```dd.save_as_hdr(img2, 'output_folder/out.tiff')``` or out.exr to save the output as HDR floating point for later processing in, for instance, Photoshop.

I really need to work on that CLI interface. I personally live in jupyter notebook but it's been hard for others to get used to.

**Comment by crowsonkb** [comment]
I just added a work-in-progress command line client, deep_dream_cli. It should be easier to do this with.
