### ISSUE TITLE
How to install on Virtualbox VM running Ubuntu?

### ISSUE THREAD

**Issue by ProGamerGov** [crowsonkb/deep_dream#8]
I am not sure what I have done wrong.

```
ubuntu@ubuntu-VirtualBox:~/caffe$ make all
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: cannot find -lhdf5_hl
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
Makefile:566: recipe for target '.build_release/lib/libcaffe.so.1.0.0-rc3' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1
ubuntu@ubuntu-VirtualBox:~/caffe$ 

```

**Comment by crowsonkb** [comment]
It looks like the HDF5 error mentioned in this Ubuntu install guide: https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide

**Comment by ProGamerGov** [comment]
I have resolved that issue, but am receiving this error now:
```
ubuntu@ubuntu-VirtualBox:~/deep_dream$ python deep_dream_cli.py --help
Traceback (most recent call last):
  File "deep_dream_cli.py", line 8, in <module>
    from types import SimpleNamespace
ImportError: cannot import name SimpleNamespace
ubuntu@ubuntu-VirtualBox:~/deep_dream$ 

```

**Comment by ProGamerGov** [comment]
```
ubuntu@ubuntu-VirtualBox:~/deep_dream$ python3 deep_dream_cli.py --help
Traceback (most recent call last):
  File "deep_dream_cli.py", line 13, in <module>
    import deep_dream as dd
  File "/home/ubuntu/deep_dream/deep_dream/__init__.py", line 1, in <module>
    from .deep_dream import CNN, EPS, ShapeError, call_normalized, normf, save_as_hdr, to_image
  File "/home/ubuntu/deep_dream/deep_dream/deep_dream.py", line 15, in <module>
    import caffe
ImportError: No module named 'caffe'
ubuntu@ubuntu-VirtualBox:~/deep_dream$ 
```

**Comment by crowsonkb** [comment]
Try setting the PYTHONPATH environment variable to the 'python' directory inside Caffe's install location, and looking at my style transfer script's requirements/install instructions in general, since these two scripts have many of the same requirements: https://github.com/crowsonkb/style_transfer

**Comment by ProGamerGov** [comment]
Thanks! That resolved the issue.

**Comment by ProGamerGov** [comment]
It seems I was installing things with pip instead of pip3.

**Comment by ProGamerGov** [comment]
CPU utilizing seems to be bouncing between 45%, and 72%, even though I have configured the Virtualbox VM to be able to use %100. Is this normal? Can I make it use the full 100%?

**Comment by crowsonkb** [comment]
That's weird. But I've seen weird things with Caffe and virtual machine / cloud machine CPU usage in the past. Using [MKL](https://software.intel.com/en-us/intel-mkl) as Caffe and NumPy's mathematics library seemed to help, especially without a GPU.
